@extends('layouts.app')

@section('content')
<main id="main" class="main-site">

    <div class="container">

        <div class="wrap-breadcrumb">
            <ul>
                <li class="item-link"><a href="/{{ LaravelLocalization::getCurrentLocale() }}/" class="link">home</a></li>
                <li class="item-link"><span>Terms & Conditions</span></li>
            </ul>
        </div>
    </div>
    
    <div class="container pb-60">
        <div class="row">
            <div class="col-md-12">
                <h3>{{__('Terms & Conditions')}}</h3>
                <h3>{{__('1-Your SSA Developer Account')}}</h3>
                <p>{{__('If you create an account on the Website, you are responsible for maintaining the security of your account, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with the account. You agree to provide and maintain accurate, current and complete information, including your contact information for notices and other communications from us and your payment information. You may not use false or misleading information in connection to your account, or trade on the name or reputation of others, and SSA Developer may change or remove any information that it considers inappropriate or unlawful, or otherwise likely to expose SSA Developer to claims of third parties. You agree that we may take steps to verify the accuracy of information you have provided to us.')}}
                    {{__('You are responsible for taking reasonable steps to maintain the confidentiality of your username and password. You must immediately notify SSA Developer of any unauthorized uses of your information, your account or any other security breaches. SSA Developer will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions.')}}</p>
                <h3>2. Responsibility of Users of the Website, Products, and/or Services</h3>
                <p>
                    Your access to, and all of your use of the Website, Products, and/or Services must be lawful and must be in compliance with these Terms, and any other agreement between you and SSA Developer.
                    When accessing or using the Website, Products, and/or Services, you must behave in a civil and respectful manner at all times. We specifically prohibit any use of the Website, Products, and/or Services, and you agree not to use the Website, for any of the following:
                    • Engaging in conduct that would constitute a criminal offense, giving rise to civil liability or otherwise violate any city, state, national or international law or regulation that would fail to comply with accepted internet protocol;
                    • Communicating, transmitting, or posting material that is copyrighted or otherwise owned by a third party unless you are the copyright owner or have the permission of the owner to post it;
                    • Communicating, transmitting, or posting material that reveals trade secrets, unless you own them or have the permission of the owner;
                    • Communicating, transmitting, or posting material that infringes on any other intellectual property, privacy or publicity right of another;
                    • Attempting to interfere in any way with the Website, or our networks or network security, or attempting to use our Website to gain unauthorized access to any other computer system;
                    • Accessing data not intended for you, or logging on to a server or account, which you are not authorized to access;
                    • Attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization (or succeeding in such an attempt);
                    • Attempting to interfere or interfering with the operation of the Website, Products, and/or Services, or our provision of Services to any other users of the Website, our hosting provider or our network, including, without limitation, via means of submitting a virus to the Website, overloading, “flooding”, “mail bombing” or “crashing” the Website.
                    In addition, if you operate an account, contribute to an account, post material to the Website, post links on the Website, or otherwise make material available by means of the Website (any such material, "Content"), you are solely responsible for the content of, and any harm and damages resulting from that Content. That is the case regardless of whether the Content in question constitutes text, graphics, an audio file, or computer software. By making Content available, you represent and warrant that:
                    • the downloading, copying and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party;
                    • if your employer has rights to intellectual property you create, you have either (i) received written permission from your employer to post or make available the Content, including but not limited to any software, or (ii) secured from your employer a written waiver as to all rights in or to the Content;
                    • you have fully complied with any third party licenses relating to the Content, and have done all things necessary to successfully pass through to end users any required terms;
                    • the Content does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content;
                    • the Content is not spam, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unethical or unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);
                    • the Content is not obscene, libelous, hateful or racially or ethnically objectionable, and does not violate the privacy or publicity rights of any third party.
                    If you delete Content, SSA Developer will use reasonable efforts to remove it from the Website and our servers, but you acknowledge that caching or references to the Content may not be made unavailable to the public immediately.
                    You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. SSA Developer shall take reasonable precautions to prevent the transmission of harmful content from its technology systems to your technology systems.
                    SSA Developer disclaims any liability for any harm or damages resulting from your access or use of the Website, Products, and/or Services, or access or use of non-SSA Developer websites.
                    SSA Developer has the right (though not the obligation) to (i) refuse or remove any Content that, in SSA Developer reasonable opinion, violates any SSA Developer policy or is in any way harmful or objectionable, or (ii) terminates or denies access to and use of the Website, Products, and/or Services, to any person for any reason, in SSA Developer sole discretion.</p>
                <h3>3. Fees and Payments</h3>
                <p>
                    By purchasing Products and/or Services, you agree to pay SSA Developer annual subscription fees indicated for such Product or Service. Payments will be due as of the first day you sign up for a Product and/or Services, and will cover an annual period, as indicated when signing up.
                    Configurations and prices of the Website, Products, and/or Services are subject to change at any time, and SSA Developer shall at all times be entitled to modify configurations, fees, prices and quotations, provided that no price changes shall be made applicable to you during a subscription term, and shall only take effect after SSA Developer and you have agreed upon an extension, upgrade or renewal of the subscription term. You agree to any such changes if you do not object in writing to SSA Developer within seven (7) business days of receiving a notice of SSA Developer, or an invoice, incorporating or announcing the fee and/or price changes. All prices are exclusive of, and you shall pay all taxes, duties, levies or fees, or other similar charges imposed on SSA Developer or yourself by any taxing authority (other than taxes imposed on SSA Developer income), related to your order, unless you have provided SSA Developer with an appropriate resale or exemption certificate for the delivery location, which is the location where the Products and/or Services are used or performed. In case of changes in law such that a tax is levied that is or becomes irrecoverable with a consequent increase to the costs to SSA Developer of delivering the Products and/or Services, whereby and to such an extent SSA Developer is entitled to increase its prices accordingly and retroactively.</p>
                <h3>4. Use of Third Party Content and Materials</h3>
                <p>SSA Developer has not reviewed, and cannot review, all of the material, including computer software, posted to the Website, and cannot therefore be responsible for that material’s content, use or effects. By operating the Website, SSA Developer does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. SSA Developer disclaims any responsibility for any harm and/or damages resulting from the use or downloading of postings of other parties on the website.</p>
                <h3>5. Content Posted on Other Websites</h3>
                <p>We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which SSA Developer.com links, and that link to SSA Developer.com. SSA Developer does not have any control over those non-SSA Developer websites and webpages, and is not responsible for their contents or their use. By linking to a non-SSA Developer website or webpage, SSA Developer does not represent or imply that it endorses such website or webpage.</p>
                <h3>6. Copyright Infringement</h3>
                <p>As SSA Developer requires others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by the Website violates your copyright, you are encouraged to notify SSA Developer. SSA Developer will, as it is able, respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. In order to bring infringing material to our attention, you must provide our DMCA Agent with the following information: (a) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyrighted work; (b) an identification of the copyrighted work and the location on the Website of the allegedly infringing work; (c) a written statement that you have a good faith belief that the disputed use is not authorized by the owner, its agent or the law; (d) your name and contact information, including telephone number and email address; and (e) a statement by you that the above information in your notice is accurate and, under penalty of perjury, that you are the copyright owner or authorized to act on the copyright owner’s behalf.
                  The contact information of our DMCA Agent for notice of claims of tartous + 99999999, email: dmca@SSA Developer.com.
                  In the case of a user who may infringe or repeatedly infringes upon the copyrights or other intellectual property rights of SSA Developer or others, SSA Developer may, in its discretion, terminate or deny access to and use of the Website, Products, and/or Services. In the case of such termination, SSA Developer will have no obligation to provide a refund of any amounts previously paid to SSA Developer to any person in respect of any such termination.</p>
                <h3>7. Trademarks</h3>
                <p>SSA Developer, the SSA Developer logo, and all other trademarks, service marks, graphics and logos used in connection with the Website, Products, and Services, are trademarks or registered trademarks of SSA Developer or SSA Developer licensors. Other trademarks, service marks, graphics and logos used in connection with the Website, Products, and Services, may be the trademarks of other third parties in which case such license is for the exclusive benefit and use of us unless otherwise stated, or may be the property of their respective owners. Your use of the Website grants you no right or license to reproduce or otherwise use any SSA Developer or third party trademarks. Likewise, you grant no right or license to reproduce or otherwise use any of your trademarks, service marks, graphics and/or logos, unless expressly authorized by you.</p>
                <h3>8. Termination</h3>
                <p>
                    You may terminate your agreement and close your account with SSA Developer at any time, effective the last day of your subscription term, by sending an email to support@SSADeveloper.com. SSA Developer may terminate its relationship with you, or may terminate or suspend the accessibility to the Website, Products, and/or Services at any time, including the use of any software, (i) if you breach these Terms and/or any other agreement with SSA Developer; (ii) if SSA Developer reasonably suspects that you are using the Website, Products, and/or Services to breach the law or infringe third party rights; (iii) if SSA Developer reasonably suspects that you are trying to unfairly exploit or misuse SSA Developer policies; (iv) if SSA Developer reasonably suspects that you are using the Website, Products, and/or Services fraudulently, or that Products or Services provided to you are being used by a third party fraudulently; (v) if you fail to pay any amounts due to SSA Developer; (vi) you violate any applicable law or regulation. Upon termination of your SSA Developer account for the above reasons, there will be no refund of fees and you will be denied access to the Website, Products and/or the Services, including all of its data.
                   SSA Developer may terminate any agreement and access to your account, if the Services or any part thereof, are no longer legally available in your jurisdiction, or are no longer commercially viable, at SSA Developer sole discretion. In case of termination or closing of your account by you because of a material breach by SSA Developer, without any default by you, or in case of a force majeure on the side of SSA Developer, SSA Developer will refund pro rata for the remaining period of your subscription any fees or expenses paid by you.
                      If you believe that SSA Developer has failed to perform or the Services are defective, you must notify SSA Developer in writing and allow fourteen (14) days for SSA Developer to cure the defect. If SSA Developer cures the defect within this cure period, SSA Developer will not be in default and cannot be held liable for any damages and/or losses in connection to such default. If SSA Developer has not cured the defect within this cure period, you may terminate the subscription with immediate effect, upon written notice to SSA Developer.
                  </p>
                
            </div>
        </div>
    </div><!--end container-->

</main>


@endsection